substitutions:
  # -----------------------
  # ADJUST DEVICE NAME HERE
  # -----------------------
  device_name: "sensecapindicator"
  device_friendly_name: "Seeed SenseCap Indicator"

  # ---------------------------------------------------------------------------------
  # ENTER API AND OTA KEY HERE
  # Add the keys to your secret file or change them here if you want individual keys.
  # ---------------------------------------------------------------------------------
  api_key: !secret api_encryption_key
  ota_key: !secret ota_password

  # ------------------------------
  # ADJUST YOUR WLAN SETTINGS HERE
  # ------------------------------
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # ----------------------------------------------------------------------------------------------------
  # ADJUST TOTAL NUMBER OF PAGES HERE
  # Is used to generate navigation dots and their logic (set it to your pages + 1 for the settings page)
  # ----------------------------------------------------------------------------------------------------
  total_pages: "2"
  
  # --------------
  # OTHER SETTINGS
  # --------------
  page_transition_time: 150ms # How long to animate the transition between pages.
  user_interface_debug_mode: "false" # Draws borders around objects and labels for layouting

packages:
  HomeDicator: !include HomeDicator/device/seeed-sensecap-indicator.yaml

sensor:
  # ----------------------------------------------------------------------
  # ADD YOUR SENSORS HERE
  # Because of the way ESPHOME works lights, thermostats, etc also go here
  # They need to be included here in order for display to update values.
  # ----------------------------------------------------------------------

  - !include
      file: HomeDicator/core/templates/sensor_battery.yaml
      vars:
        hass_sensor_id: "envoy_122310091596_battery" # You can ommit the "sensor."
  - !include
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "p1_meter_power" # You can ommit the "sensor."
  - !include
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "envoy_122310091596_current_power_production" # You can ommit the "sensor."

lvgl:  
  pages:
    # ----------------------------
    # ADD / ADJUST YOUR PAGES HERE
    # ----------------------------
    - id: first_page
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Battery"
        - obj:
            styles: content_container
            layout: 
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/battery.yaml
                  vars:
                    hass_sensor_id: "envoy_122310091596_battery"
                    title: "Charge"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: white
                    hass_sensor_id: "p1_meter_power"
                    title: "Power"
                    unit: "W"
                    icon: "\U000F140B"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: white
                    hass_sensor_id: "envoy_122310091596_current_power_production"
                    title: "Solar"
                    unit: "kW"
                    icon: "\U000F0A72"